# Configuration for Simple Web Server
pipelines:
  - name: "Simple Web Server"
    file: "src/pipelines/simple_web_pipeline.yaml"
    enabled: true

plugins:
  enabled:
    - Web.SimpleWebServer
    - Core.Logger
    - Data_Processing.PipelineControl
    - Data_Processing.ContextManager
    - Data_Processing.LLMFunction
    - AIModels.MockAIModel
    - AIModels.BaseAIModel

settings:
  pipeline_directory: "src/pipelines"
  output_directory: "output"
  log_level: "INFO"
  test_mode: false

# Web server configuration
plugin_configs:
  SimpleWebServer:
    port: 8080
    host: ""  # Empty string for all interfaces
  
  # Context manager configuration
  ContextManager:
    log_context_changes: true  # Log when context is modified