# List of pipeline definitions
pipelines:
  - name: "Simple Web Server"
    description: "A simple web server with test endpoints and context management"
    version: "1.0"
    enabled: true
    execution_mode: single
    plugin_manager_required: true  # Ensure plugin manager is passed to plugins

    steps:
      - name: "Start Web Server"
        plugin: "Web.SimpleWebServer"
        use_plugin_manager: true  # Explicitly request plugin manager for this plugin
        config:
          port: 1234
          host: "0.0.0.0"  # Listen on all interfaces
          static_dir: "public"  # Files will be served at /static/*
          default_llm_provider: "MockAIModel" # Default LLM provider for chat
          default_llm_model: "mock-model-1" # Default LLM model for chat
        
      - name: "Add Test Route"
        plugin: "Web.SimpleWebServer"
        config:
          method: "GET"
          path: "/api/test"
          handler: |
            response = 200, {
                "status": "success",
                "message": "Test endpoint working"
            }

      - name: "Add Counter Route"
        plugin: "Web.SimpleWebServer"
        config:
          method: "GET"
          path: "/api/counter"
          handler: |
            # Initialize counter if it doesn't exist
            if 'counter' not in context:
                context['counter'] = 0
            
            # Increment counter
            context['counter'] += 1
            
            response = 200, {
                "status": "success",
                "counter": context['counter']
            }

      - name: "Initialize Context Data"
        plugin: "Data_Processing.ContextManager"
        config:
          operation: set
          key: "server_info"
          value:
            name: "Test Server"
            version: "1.0.0"
            started_at: ${time.time()}

      - name: "Add Test Data"
        plugin: "Data_Processing.ContextManager"
        config:
          operation: set
          key: "test_data"
          value:
            numbers: [1, 2, 3, 4, 5]
            message: "Hello from context"
            metadata:
              author: "Pipeline"
              purpose: "Testing"

      - name: "Keep Server Running Indefinitely"
        plugin: "Data_Processing.PipelineControl"
        config:
          operation: halt
        output: server_running_indefinitely

