# This workflow runs all tests and is only triggered manually.
# It ensures plugins are discoverable and usable by setting the correct PYTHONPATH.

name: Run All Tests

on:
  workflow_dispatch:
    inputs:
      extra_args:
        description: 'Extra arguments to pass to the test runner (optional)'
        required: false

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.10']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests (pytest, with plugins)
        env:
          PYTHONPATH: .:${{ github.workspace }}/src # Set PYTHONPATH to current directory and src for module discovery
        run: |
          echo "PYTHONPATH set to: $PYTHONPATH"
          python -m pytest tests ${{ github.event.inputs.extra_args }}

      # Documentation: This workflow ensures that all tests are run with the correct PYTHONPATH so plugins can be discovered.
      # It is intended for manual use only to avoid unnecessary CI load.
